# Generated by Django 5.0.1 on 2024-02-13 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("genres", models.TextField(blank=True, null=True)),
                ("keywords", models.TextField(blank=True, null=True)),
                ("overview", models.TextField(blank=True, null=True)),
                ("vote_average", models.FloatField(blank=True, null=True)),
                ("vote_count", models.IntegerField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("watched", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Credits",
            fields=[
                (
                    "movie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="recommend.movies",
                    ),
                ),
                ("cast", models.TextField(blank=True, null=True)),
                ("director", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Metadata",
            fields=[
                (
                    "movie_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="recommend.movies",
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
