# Generated by Django 5.0.1 on 2024-02-02 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("genres", models.TextField()),
                ("keywords", models.TextField()),
                ("overview", models.TextField()),
                ("vote_average", models.FloatField()),
                ("vote_count", models.IntegerField()),
                ("year", models.IntegerField()),
                ("language", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Credits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cast", models.TextField()),
                ("crew", models.TextField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recomm.movies"
                    ),
                ),
            ],
        ),
    ]
