# Generated by Django 5.0.3 on 2024-03-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movies",
            name="watched",
        ),
        migrations.AddField(
            model_name="movies",
            name="cast",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movies",
            name="director",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movies",
            name="poster_path",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="Credits",
        ),
    ]
