# Generated by Django 5.0.1 on 2024-02-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recomm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metadata",
            fields=[
                ("movie_id", models.IntegerField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
            ],
        ),
    ]
