# Generated by Django 5.0.1 on 2024-02-04 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recomm", "0002_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credits",
            name="id",
        ),
        migrations.RemoveField(
            model_name="metadata",
            name="movie_id",
        ),
        migrations.AddField(
            model_name="metadata",
            name="movie",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="recomm.movies",
            ),
        ),
        migrations.AddField(
            model_name="movies",
            name="watched",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="credits",
            name="cast",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="credits",
            name="crew",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="credits",
            name="movie",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="recomm.movies",
            ),
        ),
        migrations.AlterField(
            model_name="movies",
            name="genres",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="movies",
            name="keywords",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="language",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="overview",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="vote_average",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="vote_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
