# Generated by Django 5.0.1 on 2024-02-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recomm", "0003_remove_credits_id_remove_metadata_movie_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="movie",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="recomm.movies",
            ),
        ),
    ]
