# Generated by Django 5.0.1 on 2024-02-04 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recomm", "0004_alter_metadata_movie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="credits",
            old_name="crew",
            new_name="director",
        ),
    ]
